/**
 * CRUD code generator
 * Generates basic Create, Read, Update, Delete operations for a module
 */

import type { ModuleDefinition, FieldDefinition, GeneratedFile } from '../types.js'

/**
 * Generate CRUD code files for a module that has data fields
 */
export function generateCrud(module: ModuleDefinition): GeneratedFile[] {
  const files: GeneratedFile[] = []

  if (!module.fields || module.fields.length === 0) return files

  const modelName = toPascalCase(module.name)
  const varName = toCamelCase(module.name)
  const fileName = toKebabCase(module.name)

  files.push(generateModel(modelName, fileName, module.fields))
  files.push(generateStore(modelName, varName, fileName, module.fields))
  files.push(generateRoutes(modelName, varName, fileName, module.fields))

  return files
}

/** Generate a TypeScript model/interface file */
function generateModel(
  modelName: string,
  fileName: string,
  fields: FieldDefinition[]
): GeneratedFile {
  const fieldLines = fields.map((f) => {
    const opt = f.required ? '' : '?'
    return `  ${f.name}${opt}: ${f.type}`
  })

  const content = `/**
 * ${modelName} data model
 * Auto-generated by code-generation-service
 */

export interface ${modelName} {
  id: string
${fieldLines.join('\n')}
  createdAt: string
  updatedAt: string
}

export interface Create${modelName}Input {
${fields
  .filter((f) => f.required)
  .map((f) => `  ${f.name}: ${f.type}`)
  .join('\n')}
${fields
  .filter((f) => !f.required)
  .map((f) => `  ${f.name}?: ${f.type}`)
  .join('\n')}
}

export interface Update${modelName}Input {
${fields.map((f) => `  ${f.name}?: ${f.type}`).join('\n')}
}
`
  return {
    path: `src/models/${fileName}.ts`,
    content,
    type: 'model',
  }
}

/** Generate a simple JSON file-based store */
function generateStore(
  modelName: string,
  varName: string,
  fileName: string,
  fields: FieldDefinition[]
): GeneratedFile {
  const content = `/**
 * ${modelName} storage module
 * Simple in-memory + JSON file storage
 * Auto-generated by code-generation-service
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { randomUUID } from 'node:crypto'
import type { ${modelName}, Create${modelName}Input, Update${modelName}Input } from '../models/${fileName}.js'

const DATA_FILE = 'data/${fileName}.json'

let ${varName}s: ${modelName}[] = []

/** Load data from JSON file */
export function load(): void {
  if (existsSync(DATA_FILE)) {
    try {
      const raw = readFileSync(DATA_FILE, 'utf-8')
      ${varName}s = JSON.parse(raw)
    } catch {
      ${varName}s = []
    }
  }
}

/** Save data to JSON file */
function save(): void {
  writeFileSync(DATA_FILE, JSON.stringify(${varName}s, null, 2))
}

/** List all ${varName}s */
export function list(): ${modelName}[] {
  return ${varName}s
}

/** Get a single ${varName} by ID */
export function getById(id: string): ${modelName} | undefined {
  return ${varName}s.find((item) => item.id === id)
}

/** Create a new ${varName} */
export function create(input: Create${modelName}Input): ${modelName} {
  const now = new Date().toISOString()
  const item: ${modelName} = {
    id: randomUUID(),
    ...input,
${fields
  .filter((f) => !f.required)
  .map((f) => `    ${f.name}: input.${f.name} ?? ${getDefaultValue(f.type)},`)
  .join('\n')}
    createdAt: now,
    updatedAt: now,
  }
  ${varName}s.push(item)
  save()
  return item
}

/** Update an existing ${varName} */
export function update(id: string, input: Update${modelName}Input): ${modelName} | null {
  const idx = ${varName}s.findIndex((item) => item.id === id)
  if (idx === -1) return null

  ${varName}s[idx] = {
    ...${varName}s[idx],
    ...input,
    updatedAt: new Date().toISOString(),
  }
  save()
  return ${varName}s[idx]
}

/** Delete a ${varName} by ID */
export function remove(id: string): boolean {
  const idx = ${varName}s.findIndex((item) => item.id === id)
  if (idx === -1) return false

  ${varName}s.splice(idx, 1)
  save()
  return true
}

// Initialize on import
load()
`
  return {
    path: `src/stores/${fileName}-store.ts`,
    content,
    type: 'model',
  }
}

/** Generate Fastify route handlers */
function generateRoutes(
  modelName: string,
  varName: string,
  fileName: string,
  _fields: FieldDefinition[]
): GeneratedFile {
  const content = `/**
 * ${modelName} API routes
 * CRUD route handlers for Fastify
 * Auto-generated by code-generation-service
 */

import type { FastifyInstance } from 'fastify'
import * as store from '../stores/${fileName}-store.js'

export async function ${varName}Routes(app: FastifyInstance): Promise<void> {
  /** List all */
  app.get('/api/${fileName}s', async (_req, reply) => {
    const items = store.list()
    return reply.send(items)
  })

  /** Get by ID */
  app.get<{ Params: { id: string } }>('/api/${fileName}s/:id', async (req, reply) => {
    const item = store.getById(req.params.id)
    if (!item) return reply.status(404).send({ error: 'Not found' })
    return reply.send(item)
  })

  /** Create */
  app.post('/api/${fileName}s', async (req, reply) => {
    const input = req.body as Parameters<typeof store.create>[0]
    const item = store.create(input)
    return reply.status(201).send(item)
  })

  /** Update */
  app.patch<{ Params: { id: string } }>('/api/${fileName}s/:id', async (req, reply) => {
    const input = req.body as Parameters<typeof store.update>[1]
    const item = store.update(req.params.id, input)
    if (!item) return reply.status(404).send({ error: 'Not found' })
    return reply.send(item)
  })

  /** Delete */
  app.delete<{ Params: { id: string } }>('/api/${fileName}s/:id', async (req, reply) => {
    const ok = store.remove(req.params.id)
    if (!ok) return reply.status(404).send({ error: 'Not found' })
    return reply.status(204).send()
  })
}
`
  return {
    path: `src/routes/${fileName}-routes.ts`,
    content,
    type: 'route',
  }
}

/** Get a default value for a TypeScript type */
function getDefaultValue(type: string): string {
  if (type.includes('string')) return "''"
  if (type.includes('number')) return '0'
  if (type.includes('boolean')) return 'false'
  if (type.includes('[]')) return '[]'
  return "''"
}

/** Convert string to PascalCase */
function toPascalCase(str: string): string {
  // If the string contains non-ASCII characters (e.g. Chinese), return as-is
  if (/[^\x00-\x7F]/.test(str)) return str.trim()
  return str
    .split(/[\s_-]+/)
    .map((w) => w.replace(/[^\w]/g, ''))
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('')
}

/** Convert string to camelCase */
function toCamelCase(str: string): string {
  const pascal = toPascalCase(str)
  return pascal.charAt(0).toLowerCase() + pascal.slice(1)
}

/** Convert string to kebab-case */
function toKebabCase(str: string): string {
  // If the string contains non-ASCII characters, just trim and join on whitespace
  if (/[^\x00-\x7F]/.test(str)) return str.trim().replace(/\s+/g, '-')
  return str
    .replace(/[^\w\s]/g, '')
    .trim()
    .split(/[\s_]+/)
    .map((w) => w.toLowerCase())
    .join('-')
}

export { toPascalCase, toCamelCase, toKebabCase }
