/**
 * Page template generator
 * Generates simple React page components based on module definitions
 */

import type { ModuleDefinition, GeneratedFile, FieldDefinition } from '../types.js'
import { toPascalCase, toKebabCase } from './crud-generator.js'

/**
 * Generate page template files for a module
 */
export function generatePageTemplate(module: ModuleDefinition): GeneratedFile[] {
  const files: GeneratedFile[] = []
  const pageName = toPascalCase(module.name)
  const fileName = toKebabCase(module.name)

  // Check if module has form-related responsibilities
  const hasForm = module.responsibilities.some(
    (r) => r.includes('表单') || r.includes('提交') || r.includes('收集')
  )

  // Check if module has list-related responsibilities
  const hasList = module.responsibilities.some(
    (r) => r.includes('列表') || r.includes('展示') || r.includes('管理')
  )

  if (hasForm && module.fields) {
    files.push(generateFormPage(pageName, fileName, module.fields))
    files.push(generateFormCSS(fileName))
  }

  if (hasList) {
    files.push(generateListPage(pageName, fileName, module.fields || []))
    files.push(generateListCSS(fileName))
  }

  // If neither form nor list, generate a basic page
  if (!hasForm && !hasList) {
    files.push(generateBasicPage(pageName, fileName, module))
    files.push(generateBasicCSS(fileName))
  }

  return files
}

/** Generate a form page component */
function generateFormPage(
  pageName: string,
  fileName: string,
  fields: FieldDefinition[]
): GeneratedFile {
  const requiredFields = fields.filter((f) => f.required)
  const optionalFields = fields.filter((f) => !f.required)
  const allFields = [...requiredFields, ...optionalFields]

  const stateLines = allFields
    .map((f) => `  const [${f.name}, set${toPascalCase(f.name)}] = useState('')`)
    .join('\n')

  const inputLines = allFields
    .map(
      (f) => `        <div className="form-group">
          <label htmlFor="${f.name}">${f.name}${f.required ? ' *' : ''}</label>
          <input
            id="${f.name}"
            type="${f.type === 'number' ? 'number' : 'text'}"
            value={${f.name}}
            onChange={(e) => set${toPascalCase(f.name)}(e.target.value)}
            placeholder="请输入${f.name}"
            ${f.required ? 'required' : ''}
          />
        </div>`
    )
    .join('\n')

  const bodyFields = allFields
    .map((f) => `        ${f.name}`)
    .join(',\n')

  const content = `/**
 * ${pageName} Form Page
 * Auto-generated by code-generation-service
 */

import { useState } from 'react'
import './${fileName}-form.css'

export default function ${pageName}Form() {
  const [submitting, setSubmitting] = useState(false)
  const [message, setMessage] = useState('')
${stateLines}

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setSubmitting(true)
    setMessage('')

    try {
      const res = await fetch('/api/${fileName}s', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
${bodyFields}
        }),
      })

      if (res.ok) {
        setMessage('提交成功！')
${allFields.map((f) => `        set${toPascalCase(f.name)}('')`).join('\n')}
      } else {
        setMessage('提交失败，请重试')
      }
    } catch {
      setMessage('网络错误，请稍后再试')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="${fileName}-form">
      <h2>${pageName}</h2>
      {message && <p className="message">{message}</p>}
      <form onSubmit={handleSubmit}>
${inputLines}
        <button type="submit" disabled={submitting}>
          {submitting ? '提交中...' : '提交'}
        </button>
      </form>
    </div>
  )
}
`
  return {
    path: `src/pages/${fileName}-form.tsx`,
    content,
    type: 'component',
  }
}

/** Generate a list page component */
function generateListPage(
  pageName: string,
  fileName: string,
  fields: FieldDefinition[]
): GeneratedFile {
  const displayFields = fields.length > 0 ? fields : [
    { name: 'id', type: 'string', required: true },
    { name: 'name', type: 'string', required: true },
  ]

  const headerCells = displayFields
    .map((f) => `            <th>${f.name}</th>`)
    .join('\n')

  const bodyCells = displayFields
    .map((f) => `            <td>{item.${f.name}}</td>`)
    .join('\n')

  const content = `/**
 * ${pageName} List Page
 * Auto-generated by code-generation-service
 */

import { useState, useEffect } from 'react'
import './${fileName}-list.css'

interface ${pageName}Item {
  id: string
${displayFields.map((f) => `  ${f.name}: ${f.type}`).join('\n')}
  createdAt: string
  updatedAt: string
}

export default function ${pageName}List() {
  const [items, setItems] = useState<${pageName}Item[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    fetchItems()
  }, [])

  async function fetchItems() {
    try {
      const res = await fetch('/api/${fileName}s')
      if (res.ok) {
        const data = await res.json()
        setItems(data)
      }
    } catch {
      console.error('Failed to fetch items')
    } finally {
      setLoading(false)
    }
  }

  if (loading) return <p>加载中...</p>

  return (
    <div className="${fileName}-list">
      <h2>${pageName}列表</h2>
      {items.length === 0 ? (
        <p>暂无数据</p>
      ) : (
        <table>
          <thead>
            <tr>
${headerCells}
              <th>创建时间</th>
            </tr>
          </thead>
          <tbody>
            {items.map((item) => (
              <tr key={item.id}>
${bodyCells}
                <td>{new Date(item.createdAt).toLocaleString()}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  )
}
`
  return {
    path: `src/pages/${fileName}-list.tsx`,
    content,
    type: 'component',
  }
}

/** Generate a basic page for modules without form or list */
function generateBasicPage(
  pageName: string,
  fileName: string,
  module: ModuleDefinition
): GeneratedFile {
  const content = `/**
 * ${pageName} Page
 * Auto-generated by code-generation-service
 */

import './${fileName}.css'

export default function ${pageName}Page() {
  return (
    <div className="${fileName}-page">
      <h1>${module.name}</h1>
      <p>${module.description}</p>
${
  module.components
    ? module.components.map((c) => `      <section className="section">${c}</section>`).join('\n')
    : '      <section className="section">内容区域</section>'
}
    </div>
  )
}
`
  return {
    path: `src/pages/${fileName}.tsx`,
    content,
    type: 'component',
  }
}

/** Generate form CSS */
function generateFormCSS(fileName: string): GeneratedFile {
  return {
    path: `src/pages/${fileName}-form.css`,
    content: `.${fileName}-form {
  max-width: 480px;
  margin: 0 auto;
  padding: 24px;
}
.${fileName}-form .form-group {
  margin-bottom: 16px;
}
.${fileName}-form label {
  display: block;
  margin-bottom: 4px;
  font-weight: 600;
}
.${fileName}-form input {
  width: 100%;
  padding: 8px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-sizing: border-box;
}
.${fileName}-form button {
  padding: 10px 24px;
  background: #1677ff;
  color: #fff;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}
.${fileName}-form button:disabled {
  opacity: 0.6;
}
.${fileName}-form .message {
  padding: 8px;
  background: #f0f9eb;
  border-radius: 4px;
}
`,
    type: 'component',
  }
}

/** Generate list CSS */
function generateListCSS(fileName: string): GeneratedFile {
  return {
    path: `src/pages/${fileName}-list.css`,
    content: `.${fileName}-list {
  padding: 24px;
}
.${fileName}-list table {
  width: 100%;
  border-collapse: collapse;
}
.${fileName}-list th,
.${fileName}-list td {
  padding: 8px 12px;
  border: 1px solid #e8e8e8;
  text-align: left;
}
.${fileName}-list th {
  background: #fafafa;
  font-weight: 600;
}
.${fileName}-list tr:hover {
  background: #f5f5f5;
}
`,
    type: 'component',
  }
}

/** Generate basic page CSS */
function generateBasicCSS(fileName: string): GeneratedFile {
  return {
    path: `src/pages/${fileName}.css`,
    content: `.${fileName}-page {
  max-width: 960px;
  margin: 0 auto;
  padding: 24px;
}
.${fileName}-page .section {
  margin: 16px 0;
  padding: 16px;
  background: #fafafa;
  border-radius: 8px;
}
`,
    type: 'component',
  }
}
